server.port=5000

spring.data.mongodb.uri=mongodb+srv://Admin:admin1234@cluster0.otjz2ww.mongodb.net/eventhub?appName=Cluster0

# Note: In production, the password should be handled via environment variables
jwt.secret=supersecretkey123supersecretkey123supersecretkey123supersecretkey123
